name: Portfolio-Test
favicon: null
layout_spectrum: 0.12006930238567293
typography_spectrum: 0.930358484853059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2025885891634971
  lightness: 0.9248682949692011
  saturation: 0.12783322017639875
  rhythmicContrast: 0.9652866581454873
purpose: []
